name: "Create Repository Secrets"

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main
  workflow_dispatch:  # Allows manual execution

permissions:
  actions: write
  contents: read

jobs:
  create-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Template Repository
        run: |
          git clone https://github.com/sarthaksharma22/template-automation-repo.git
          ls -la template-automation-repo/scripts  # ✅ Debugging step

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install PyGithub

      - name: Run Secret Creation Script
        run: python template-automation-repo/scripts/create_secrets.py
        env:
          GITHUB_TOKEN: ${{ secrets.PATT_TOKEN }}  # ✅ Use PAT for authentication
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Debugging Output
        if: failure()
        run: |
          echo "🚨 Script failed! Listing files in repo:"
          ls -la
